In [27]:
import numpy as np
import time


In [ ]:
#TASK-1  
# 1.Create a 1D NumPy array of 10 integers ranging from 1 to 10.

n1=np.arange(1,11)

# Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
n2=np.arange(1,10).reshape(3,3)

# Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3). 
n3=np.random.rand(3,5,3)

# 2. Display the shape, size, and datatype of each array.
print("1d array:-", n1)
print("Shape- ", n1.shape)
print("Size- ",n1.size)
print("Datatype- ",n1.dtype)

print("\n2d array:-", n2)
print("Shape- ", n2.shape)
print("Size- ",n2.size)
print("Datatype- ",n2.dtype)

print("\n3d array:-", n3)
print("Shape- ", n3.shape)
print("Size- ",n3.size)
print("Datatype- ",n3.dtype)



1d array:- [ 1  2  3  4  5  6  7  8  9 10]
Shape-  (10,)
Size-  10
Datatype-  int64

2d array:- [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape-  (3, 3)
Size-  9
Datatype-  int64

3d array:- [[[0.38939194 0.27193696 0.90901027]
  [0.64179353 0.97116316 0.25337648]
  [0.73993835 0.56148361 0.79818336]
  [0.05223986 0.96629241 0.71400851]
  [0.68385983 0.46299727 0.8448023 ]]

 [[0.80648673 0.0463565  0.98922686]
  [0.87443351 0.99601192 0.58977052]
  [0.86811881 0.63330896 0.04753257]
  [0.48262004 0.15764886 0.75715211]
  [0.79129357 0.51134256 0.40766274]]

 [[0.06490224 0.05213293 0.42535699]
  [0.27088562 0.65032642 0.89082361]
  [0.62263581 0.39148682 0.84803887]
  [0.12064589 0.17720037 0.2579105 ]
  [0.55492489 0.96526367 0.78120265]]]
Shape-  (3, 5, 3)
Size-  45
Datatype-  float64


In [18]:
#TASK-2
data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
n1=np.array(data)
n1

#  displaying the results
print("First 3 elements:- ", n1[:3])
print("\nEvery Alternative element:-", n1[::2])
print("\nReversed array:-", n1[::-1])

First 3 elements:-  [10 20 30]

Every Alternative element:- [10 30 50 70 90]

Reversed array:- [90 80 70 60 50 40 30 20 10]


In [7]:
#TASK-3
A=np.random.randint(1,21, size=5)
B=np.random.randint(1,21, size=5)
print("Array A:-", A)
print("Array B:-",B)

#  Add, subtract, multiply, and divide the two arrays elementwise. 
print("Addition:-", A+B)
print("Subtraction:-", A-B)
print("Mutiplication:-", A*B)
print("Division:-", A/B)

#Compute the dot product of the arrays. 
print("Dot Product of A&B:-", np.dot(A,B))

# Find the mean, median, standard deviation, and variance of array A. 
print("Mean of A:-", np.mean(A))
print("Median of A:-", np.median(A))
print("Standard Deviation of A:-", np.std(A))
print("Variance of A:-", np.var(A))

#Identify the maximum and minimum values in array B and their indices. 
print("Maximum of B:-", np.max(B), "at index", np.argmax(B))
print("Minimum of B:-", np.min(B), "at index", np.argmin(B))


Array A:- [15 13 15 14  9]
Array B:- [ 4  7 10  8 19]
Addition:- [19 20 25 22 28]
Subtraction:- [ 11   6   5   6 -10]
Mutiplication:- [ 60  91 150 112 171]
Division:- [3.75       1.85714286 1.5        1.75       0.47368421]
Dot Product of A&B:- 584
Mean of A:- 13.2
Median of A:- 14.0
Standard Deviation of A:- 2.227105745132009
Variance of A:- 4.96
Maximum of B:- 19 at index 4
Minimum of B:- 4 at index 0


In [16]:
#TASK-4
arr_1d=np.arange(1,13)
print("arr_1d:", arr_1d)
# Reshape the array into a 2D array of shape (4, 3).
print("2d array:-", arr_1d.reshape(4,3))
 
# Reshape the array into a 3D array of shape (2, 2, 3). 
print("3d array:-", arr_1d.reshape(2,2,3))

# Transpose the reshaped 2D array and display its shape.
print("Transpose of 2d array:-", arr_1d.reshape(4,3).T)
print("Size of Transposed array:-", arr_1d.reshape(4,3).T.shape)

arr_1d: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2d array:- [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3d array:- [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Transpose of 2d array:- [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Size of Transposed array:- (3, 4)


In [18]:
#TASK-5
arr=np.random.randint(10,50, size=15)
print("Original Array:- ", arr)

# Find all elements greater than 25. 
print("Elements greater than 25:-", arr[arr>25])

# Replace all elements less than 30 with 0. 
print("Array after replacing elements:- ", np.where(arr<30, 0, arr))

# Count the number of elements divisible by 5.
print("Count of elements divisible by 5:- ", np.sum(arr%5==0))

Original Array:-  [39 11 40 41 44 12 18 48 18 26 27 40 35 43 39]
Elements greater than 25:- [39 40 41 44 48 26 27 40 35 43 39]
Array after replacing elements:-  [39  0 40 41 44  0  0 48  0  0  0 40 35 43 39]
Count of elements divisible by 5:-  3


In [26]:
#TASK-6
# Create an array of 10 equally spaced values between 0 and 1. 
eqsparr= np.linspace(0,1,10)
print("Original array:-", eqsparr)

# Create an identity matrix of size 4x4. 
print("\nIdentity Matrix:-", np.eye(4))

# Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements. 
array=np.random.randint(1,100, size=20)
print("Random Array:-", array)
print("Sorted Array:- ", np.sort(array))
print("5 largest elements:- ", np.sort(array)[-5:])


Original array:- [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Identity Matrix:- [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random Array:- [35 75 36 64 76 38 10 48 78 32 27 59 12 93 50 64 38 88 10 43]
Sorted Array:-  [10 10 12 27 32 35 36 38 38 43 48 50 59 64 64 75 76 78 88 93]
5 largest elements:-  [75 76 78 88 93]


In [30]:
#TASK-7
# Generates two large random arrays of size (100, 100). 
A=np.random.rand(100,100)
B=np.random.rand(100, 100)

#Time before performing operations
start_time=time.time()

# Performs matrix multiplication on the two arrays. 
mul_mat=np.matmul(A,B)
print("Matrix Multiplication:-\n ",mul_mat)

# Finds the determinant and inverse of the resulting matrix (if possible).
det=np.linalg.det(np.matmul(A,B))
print("\nDeterminant of Matrix:- ", det)

if det!=0:
    inv=np.linalg.inv(mul_mat)
    print("Inverse if determinant is not zero:- ", inv)
else:
    print("Sorry!, Inverse doesn't exist")
print("Inverse computed successfully.")

# Measures the time taken to complete given operations.
end_time=time.time()
print("\nTotal Time taken to complete given  operations:- ", start_time - end_time)



Matrix Multiplication:-
  [[23.58850188 24.80450055 24.38316897 ... 23.44098524 23.192426
  26.91394719]
 [26.30060171 24.44116638 25.48773284 ... 24.08147141 25.7289754
  26.90076834]
 [22.92630747 21.4607922  23.95091679 ... 21.57841147 20.23765045
  20.08445309]
 ...
 [24.18332912 27.16250129 24.82531764 ... 23.60439795 23.67186969
  24.53118898]
 [24.13863396 26.29591929 25.59699759 ... 23.29376139 24.90488065
  25.76645114]
 [26.18548662 23.86459219 25.56907387 ... 22.84887485 26.37972238
  25.57904767]]

Determinant of Matrix:-  1.5444109247271105e+49
Inverse if determinant is not zero:-  [[-3.24703642  0.19055777  1.33009505 ...  0.69667012 -0.13571777
  -2.5305206 ]
 [ 4.70582644 -0.52226715 -1.78046045 ... -0.77107988  0.18048565
   3.01739883]
 [ 1.57906385 -0.10649318 -0.14785776 ... -0.05538126  0.33534073
   0.08926909]
 ...
 [-1.88445412 -0.09235144  0.60682426 ...  0.37565074  0.09924024
  -1.53177303]
 [ 4.83287826  0.114639   -1.89761356 ... -0.45999951 -0.22323787
   